### ISSUE TITLE
Change Password LDAP + Local Machine breaks hard

### ISSUE THREAD

**Issue by gregwkeller** [MutonUfoAI/pgina#122]
Using the 3.9.9.12 version with Windows 10 Home

I have a LDAP authentication, and the Local user DB

If I enable change password on Local Machine it breaks the change password on the LDAP module until I reinstall.  

Currently, in order to login I need to either:
1) delete user from local DB using Local Machine plugin option in Notification 
or
2) change LDAP using [CTL][ALT][DEL] pGina window, then change the local password using the Control Panel password option or netplwiz.  Is there any way to have pGina update both LDAP and Local Machine?

If I use [CTL][ALT][DEL] and change the password, then use the _same_ password as the new password it works and exits with a message that my Local Password has been updated.  Log file looks happy and shows LDAP being updated too.

If I use [CTL][ALT][DEL] and change the password, then use a _different_ password as the new password it exits and says "pGina: your password has been changed".  The local password has actually changed but not the LDAP password so they are out of sync.  Even if I do not check the box authenticate or authorization box for using the Local Machine plugin it still fails if I use the current LDAP password.  I must log in with the now Local User password and then change the LDAP password manually to get them synchronized again.

The relevant log info from a failed attempt compared to the successful log is:
"2018-07-16 22:26:01,373 [3560|22|DEBUG] pGina.Service.Impl: Processing ChangePasswordRequest for: MyLDAPuserName domain: SEAT1 session: 1
2018-07-16 22:26:01,389 [3560|22|INFO ] pGina.Service.Impl: domain:SEAT1
2018-07-16 22:26:01,389 [3560|22|INFO ] pGina.Service.Impl: domain:SEAT1
2018-07-16 22:26:01,404 [3560|22|DEBUG] pGina.Service.Impl: no SessionProperties cached for user:MyLDAPuserName
2018-07-16 22:26:01,420 [3560|22|ERROR] Abstractions: GetDomainInfo() Error:1355 The specified domain either does not exist or could not be contacted
2018-07-16 22:26:01,420 [3560|22|INFO ] pGina.Service.Impl: DomainMember
2018-07-16 22:26:01,607 [3560|32|DEBUG] RemoteLog[NativeLib]: [Credential.cpp:472] change password success
2018-07-16 22:26:08,311 [3560|23|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:281] Provider::UnAdvise() - provider events callback reference released
2018-07-16 22:26:08,342 [3560|9|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:102] Stopping service state helper thread (if necessary)"

When it works, it looks like....
"2018-07-16 22:19:50,968 [3628|3|DEBUG] pGina.Service.Impl: Processing ChangePasswordRequest for: MyLDAPuserName domain: SEAT1 session: 2
2018-07-16 22:19:50,968 [3628|3|INFO ] pGina.Service.Impl: domain:SEAT1
2018-07-16 22:19:50,984 [3628|3|INFO ] pGina.Service.Impl: domain:SEAT1
2018-07-16 22:19:51,015 [3628|3|DEBUG] pGina.Service.Impl: ChangePassword: executing 0f52390b-c781-43ae-bd62-553c77fa4cf7
2018-07-16 22:19:51,015 [3628|3|DEBUG] LdapPlugin: ChangePassword()
... a bunch of ldap to change the 3 different passwords ...
"
So is there an obvious reason the domain becomes unfindable ("|ERROR] Abstractions: GetDomainInfo() Error:1355 The specified domain either does not exist or could not be contacted") once the Local Machine Change Password has been selected - even after it has been disabled?

Any reason un-checking Local Machine plugin's Change Password is not returning the system to a state where the LDAP Plugin's Change Password can succeed?

I've tried reversing the order of the Change Password plugins, but same results.
 
Cheers!

**Comment by MutonUfoAI** [comment]
Working ....
I hope you don't try to reset the user password on the login screen (reset pwd after next logon)
because Win10 broke that.

success

2018-07-17 12:33:49,156 [1616|24|DEBUG] pGina.Service.Impl: Processing ChangePasswordRequest for: user001 domain: 7X64E session: 1
2018-07-17 12:33:49,156 [1616|24|INFO ] pGina.Service.Impl: domain:7X64E
2018-07-17 12:33:49,156 [1616|24|INFO ] pGina.Service.Impl: domain:7X64E
2018-07-17 12:33:49,156 [1616|24|DEBUG] pGina.Service.Impl: ChangePassword: executing 0f52390b-c781-43ae-bd62-553c77fa4cf7
2018-07-17 12:33:49,156 [1616|24|DEBUG] LdapPlugin: ChangePassword()
2018-07-17 12:33:49,156 [1616|24|DEBUG] LdapServer: Initializing LdapServer host(s): [student00i.students.mydomain.gov.org], port: 389, useSSL = False, useTLS = False, verifyCert = False
2018-07-17 12:33:49,172 [1616|24|DEBUG] LdapServer: Timeout set to 30 seconds.
2018-07-17 12:33:49,172 [1616|24|DEBUG] LdapServer: Attempting to bind with DN uid=user001,ou=users,dc=students,dc=mydomain,dc=gov,dc=org
2018-07-17 12:33:49,172 [1616|24|DEBUG] LdapServer: Attempting bind as uid=user001,ou=users,dc=students,dc=mydomain,dc=gov,dc=org
2018-07-17 12:33:49,218 [1616|24|DEBUG] LdapServer: Successful bind to student00i.students.mydomain.gov.org as uid=user001,ou=users,dc=students,dc=mydomain,dc=gov,dc=org
2018-07-17 12:33:49,234 [1616|24|DEBUG] LdapServer: LDAP DN uid=user001,ou=users,dc=students,dc=mydomain,dc=gov,dc=org successfully bound to server, return success
2018-07-17 12:33:49,234 [1616|24|INFO ] LdapServer: ntplist:student00i.students.mydomain.gov.org ts1.mydomain.gov.org ts2.mydomain.gov.org 
2018-07-17 12:33:49,234 [1616|24|DEBUG] LdapServer: convert attrib:[cn] to [Fullname] value:[user 001]
2018-07-17 12:33:49,234 [1616|24|DEBUG] LdapServer: convert attrib:[mail] to [Email] value:[user001@mydomain.gov.org]
2018-07-17 12:33:49,250 [1616|24|DEBUG] LdapPlugin: Setting attribute sambaLMPassword using method LM Hash (sambaLMPassword, DES)
2018-07-17 12:33:49,656 [1616|24|DEBUG] LdapPlugin: Setting attribute sambaNTPassword using method NTLM Hash (sambaNTPassword, MD4)
2018-07-17 12:33:49,671 [1616|24|DEBUG] LdapPlugin: Setting attribute userPassword using method SSHA1 (Salted SHA1)
2018-07-17 12:33:49,671 [1616|24|DEBUG] LdapPlugin: Setting attribute shadowLastChange using method Timestamp days since '70
2018-07-17 12:33:49,671 [1616|24|DEBUG] LdapPlugin: Setting attribute sambaPwdLastSet using method Timestamp sec since '70
2018-07-17 12:33:49,671 [1616|24|DEBUG] LdapServer: Closing LDAP connection to student00i.students.mydomain.gov.org.
2018-07-17 12:33:49,687 [1616|24|DEBUG] pGina.Service.Impl: ChangePassword: result from 0f52390b-c781-43ae-bd62-553c77fa4cf7 is True message: LDAP password successfully changed
2018-07-17 12:33:49,687 [1616|24|DEBUG] pGina.Service.Impl: ChangePassword: executing 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d
2018-07-17 12:33:49,687 [1616|24|DEBUG] LocalMachine: ChangePassword()
2018-07-17 12:33:49,687 [1616|24|DEBUG] LocalMachine: Authenticated via old password: user001
2018-07-17 12:33:49,702 [1616|24|DEBUG] LocalMachine: Found principal, changing password for user001
2018-07-17 12:33:49,702 [1616|24|DEBUG] pGina.Service.Impl: ChangePassword: result from 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d is True message: Local password successfully changed.
2018-07-17 12:33:49,702 [1616|26|DEBUG] RemoteLog[NativeLib]: [Credential.cpp:472] change password success

fail

2018-07-17 12:47:40,153 [1616|26|DEBUG] pGina.Service.Impl: Processing ChangePasswordRequest for: user001 domain: 7X64E session: 1
2018-07-17 12:47:40,153 [1616|26|INFO ] pGina.Service.Impl: domain:7X64E
2018-07-17 12:47:40,184 [1616|26|INFO ] pGina.Service.Impl: domain:7X64E
2018-07-17 12:47:40,184 [1616|26|DEBUG] pGina.Service.Impl: ChangePassword: executing 0f52390b-c781-43ae-bd62-553c77fa4cf7
2018-07-17 12:47:40,184 [1616|26|DEBUG] LdapPlugin: ChangePassword()
2018-07-17 12:47:40,184 [1616|26|DEBUG] LdapServer: Initializing LdapServer host(s): [student00i.students.mydomain.gov.org], port: 389, useSSL = False, useTLS = False, verifyCert = False
2018-07-17 12:47:40,184 [1616|26|DEBUG] LdapServer: Timeout set to 30 seconds.
2018-07-17 12:47:40,184 [1616|26|DEBUG] LdapServer: Attempting to bind with DN uid=user001,ou=users,dc=students,dc=mydomain,dc=gov,dc=org
2018-07-17 12:47:40,200 [1616|26|DEBUG] LdapServer: Attempting bind as uid=user001,ou=users,dc=students,dc=mydomain,dc=gov,dc=org
2018-07-17 12:48:01,310 [1616|26|ERROR] LdapServer: LdapException: 81 The LDAP server is unavailable. 
2018-07-17 12:48:01,341 [1616|26|ERROR] LdapPlugin: Exception in ChangePassword: System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
   at pGina.Plugin.Ldap.LdapServer.Bind(NetworkCredential creds)
   at pGina.Plugin.Ldap.LdapServer.Authenticate(String uname, String password, SessionProperties properties)
   at pGina.Plugin.Ldap.LdapPlugin.ChangePassword(SessionProperties properties, ChangePasswordPluginActivityInfo pluginInfo)
2018-07-17 12:48:01,357 [1616|26|DEBUG] LdapServer: Closing LDAP connection to .
2018-07-17 12:48:01,357 [1616|26|DEBUG] pGina.Service.Impl: ChangePassword: result from 0f52390b-c781-43ae-bd62-553c77fa4cf7 is False message: Error in LDAP plugin.
2018-07-17 12:48:01,856 [1616|29|DEBUG] RemoteLog[NativeLib]: [Credential.cpp:452] pGina::Transactions::User::ProcessChangePasswordForUser failed: Error in LDAP plugin.
2018-07-17 12:48:03,994 [1616|27|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:281] Provider::UnAdvise() - provider events callback reference released
2018-07-17 12:48:04,243 [1616|23|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:102] Stopping service state helper thread (if necessary)

![bild5](https://user-images.githubusercontent.com/2519674/42813360-058ced82-89c1-11e8-8c0a-09ca9e07b9b8.png)
![bild3](https://user-images.githubusercontent.com/2519674/42813361-07151b16-89c1-11e8-8548-37cf676e4f18.png)

**Comment by gregwkeller** [comment]
Definitely not using the login screen password reset.  

Three things I see that are different so far:
1) The TLS is off (and unverified)  - I can test if that's a factor but recall getting "strong password required" errors which is why I set it all up
2) The fail you posted is very different; I'm getting not getting an LDAP module error, its a case of missing cache/properties "pGina.Service.Impl: no SessionProperties cached for user:MyLDAPuserName"
3)  I don't set the shadowLastChange or sambaPwdLastSet - I  can test if that makes any difference

Any hint on possible causes for #2 ? 

I'll try and do some screen grabs and testing later tonight.

Cheers!
Greg

**Comment by gregwkeller** [comment]
Actually, the problem seems more basic.  After enabling both plugins for login, neither are launched.  I noticed the "success" message changes on the [CTL]][ALT][DEL] change password screen.  Here's the entire log - not mentioning LDAP or Local Machine.... 

2018-07-17 08:25:29,914 [3576|28|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:95] Starting service state helper thread
2018-07-17 08:25:29,930 [3576|13|DEBUG] RemoteLog[NativeLib]: [CredentialProviderFilter.cpp:74] CredentialProviderFilter::Filter
2018-07-17 08:25:29,961 [3576|26|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:129] Provider::SetUsageScenario(3, 0x00000000)
2018-07-17 08:25:29,977 [3576|12|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:270] Provider::Advise(0000011CDE438340, 0000000000000009) - provider events callback reference added
2018-07-17 08:25:29,992 [3576|25|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:439] SerializedUserNameAvailable: No serialized creds set
2018-07-17 08:25:30,008 [3576|3|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:439] SerializedUserNameAvailable: No serialized creds set
2018-07-17 08:25:30,024 [3576|31|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:456] SerializedPasswordAvailable: No serialized creds set
2018-07-17 08:25:30,039 [3576|30|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:473] SerializedDomainNameAvailable: No serialized creds set
2018-07-17 08:25:30,070 [3576|18|DEBUG] RemoteLog[NativeLib]: [Credential.cpp:177] Credential::GetBitmapValue: Loading image from: C:\Program Files\pGina\cvlogo.bmp
2018-07-17 08:25:41,157 [3576|17|DEBUG] pGina.Service.Impl: Processing ChangePasswordRequest for: gkeller domain: SEAT1 session: 2
2018-07-17 08:25:41,174 [3576|17|INFO ] pGina.Service.Impl: domain:SEAT1
2018-07-17 08:25:41,174 [3576|17|INFO ] pGina.Service.Impl: domain:SEAT1
2018-07-17 08:25:41,190 [3576|17|DEBUG] pGina.Service.Impl: no SessionProperties cached for user:gkeller
2018-07-17 08:25:41,190 [3576|17|ERROR] Abstractions: GetDomainInfo() Error:1355 The specified domain either does not exist or could not be contacted
2018-07-17 08:25:41,206 [3576|17|INFO ] pGina.Service.Impl: DomainMember
2018-07-17 08:25:41,409 [3576|32|DEBUG] RemoteLog[NativeLib]: [Credential.cpp:472] change password success
2018-07-17 08:25:43,689 [3576|24|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:281] Provider::UnAdvise() - provider events callback reference released
2018-07-17 08:25:43,704 [3576|21|DEBUG] RemoteLog[NativeLib]: [Provider.cpp:102] Stopping service state helper thread (if necessary)

![image](https://user-images.githubusercontent.com/18729144/42820555-0f63544c-899c-11e8-91f0-805ac79eb760.png)


![image](https://user-images.githubusercontent.com/18729144/42819925-7913ba5a-899a-11e8-9476-5f384d35d62a.png)

**Comment by gregwkeller** [comment]
I am noticing that the LDAP Plugin plugin's change password feature seems to use the local password for the "old password" test.  So if we can get the Plugin to only test the old password from LDAP and just ignore if the local password matches I can work around the rest.

Essentially, the current problem is:

A) NewUser logs into a machine with a password from LDAP
B) pGina creates a local account for NewUser with password "XXX"
C) user hits [CTL][ALT][DEL] to change password and uses "XXX" for old password and "YYY" for new password
D) Only LDAP gets updated.  So NewUser has Local Password "XXX" but LDAP Password "YYY"
E) NewUser Logs out.  
F) NewUser Login with password "YYY" fails because pGina is using the Local Password which was never updated
G) NewUser Login with password "XXX" succeeds but can only be changed via non-pGina password Utilities manually on any seat they use.

If I enable Local Machine plugin's Change Password both LDAP Plugin _and_ Local Machine Plugin Change Password function isn't called (bug?).

**Comment by gregwkeller** [comment]
I got it to work with both Change Password options enabled until I rebooted.  Now it's failing.  Something is breaking both Plugins on reboot when the "Local Machine" Plugin "Change Password" is enabled.

**Comment by gregwkeller** [comment]
Update - I removed all the plugin DLL's from the directory except LocalMachine and LDAP.  They are working fine now.  Somehow, DLL's that aren't enabled are breaking the process just by being present?

**Comment by gregwkeller** [comment]
Still broken.  I've determined that: 
First: Reverse the Plugin Order for Change Password between Local Machine and LDAP
Second: Log Out and Back in
Third: [CTL][ALT][DEL] Change Password
... then all works as expected until the next logout or reboot.

**Comment by gregwkeller** [comment]
A key to the fix appears to be login with the HOSTNAME\AnyUserName one time and it generally works as expected after that for every user.
