### ISSUE TITLE
Automatic Account Removal doesn't work?

### ISSUE THREAD

**Issue by tristanball** [MutonUfoAI/pgina#34]
On Windows Server 2012 R2, pGina Fork version 3.2.4.1

The automatic account removal fails. In the log we see:

2016-05-26 18:21:30,975 [4908|35|DEBUG] LocalAccount[xxx]: removing SessionData 'SOFTWARE\Microsoft\Windows\CurrentVersion\NetCache\PurgeAtNextLogoff\S-1-5-21-4268648614-1336256566-3659752958-1041'
2016-05-26 18:21:30,975 [4908|35|ERROR] pGina.Service.Exception: CurrentDomain_UnhandledException: System.NullReferenceException: Object reference not set to an instance of an object.
   at pGina.Plugin.LocalMachine.LocalAccount.RemoveUserAndProfile(String user, Int32 sessionID)
   at pGina.Plugin.LocalMachine.PluginImpl.cleanup(UserInformation userInfo, Int32 sessionID)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

Help? Happy to provide whatever further info you need.

Thanks,
T

**Comment by MutonUfoAI** [comment]
fixed already
https://github.com/MutonUfoAI/pgina/releases
