### ISSUE TITLE
Cant login to pGina Account

### ISSUE THREAD

**Issue by rlkarthik** [MutonUfoAI/pgina#35]
I cant login pGina User in the windows 8 64 bit . In the Log i Observed this is the issue

2016-03-01 16:13:27,245 [2208|25|DEBUG] LocalAccount[Ora4Treat]: SyncToLocalUser()
2016-03-01 16:13:27,263 [2208|25|ERROR] PluginDriver:76cd2828-609c-41ea-a397-c5f1a3e9cdd8: 12fa152d-a2e3-4c8d-9535-5dcd49dfcb6d Failed to process gateway for Ora4Treat message: Unexpected error while syncing user's info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: The system is not authoritative for the specified account and therefore cannot complete the operation. Please retry the operation using the provider associated with this account. If this is an online provider please use the provider's online site.

--- End of inner exception stack trace ---
at System.DirectoryServices.DirectoryEntry.Invoke(String methodName, Object[] args)
at pGina.Plugin.LocalMachine.LocalAccount.SyncUserPrincipalInfo(UserPrincipal user, UserInformation info)
at pGina.Plugin.LocalMachine.LocalAccount.SyncToLocalUser()
at pGina.Plugin.LocalMachine.PluginImpl.AuthenticatedUserGateway(SessionProperties properties)
2016-03-01 16:13:27,263 [2208|25|DEBUG] PluginDriver:76cd2828-609c-41ea-a397-c5f1a3e9cdd8: End login chain, 1 stateful plugin(s).
2016-03-01 16:13:27,263 [2208|25|DEBUG] LdapPlugin: EndChain

**Comment by rlkarthik** [comment]
![4ef02132-2e75-11e6-8796-1ec7d429df80](https://cloud.githubusercontent.com/assets/19838625/15998190/e56a7004-3159-11e6-9452-cf1e57ebdbfc.png)

**Comment by MutonUfoAI** [comment]
log and configuration!

**Comment by rlkarthik** [comment]
Authored the thread means can you please explain and tell how to resolve it.
--------- Original Message --------- Subject: Re: [MutonUfoAI/pgina] Cant login to pGina Account (#35)

**Comment by rlkarthik** [comment]
pgina log is attached.
--------- Original Message --------- Subject: Re: [MutonUfoAI/pgina] Cant login to pGina Account (#35)

**Comment by rlkarthik** [comment]
Any updates.
--------- Original Message --------- Subject: Re: [MutonUfoAI/pgina] Cant login to pGina Account (#35)

**Comment by MutonUfoAI** [comment]
no log
no update ....

**Comment by rlkarthik** [comment]
Log attached
 
--------- Original Message --------- Subject: Re: [MutonUfoAI/pgina] Cant login to pGina Account (#35)

**Comment by MutonUfoAI** [comment]
you ar'nt using this fork!

**Comment by rlkarthik** [comment]
Now you got log files and before i send zip files.
 
--------- Original Message --------- Subject: Re: [MutonUfoAI/pgina] Cant login to pGina Account (#35)

**Comment by rlkarthik** [comment]
Which fork sorry i didnt get

**Comment by MutonUfoAI** [comment]
this is a pgina fork
but you are using the original pgina

**Comment by rlkarthik** [comment]
So can you suggest where have to raise and assign

**Comment by rlkarthik** [comment]
In github pgina issues i have already raised but no reply from there and the issue number is #306

**Comment by MutonUfoAI** [comment]
im unable to help you
i not working with the original src anymore

use this fork or wait 4 a response

**Comment by rlkarthik** [comment]
can you just tell why this issue is happen so that i will go to further
 
--------- Original Message --------- Subject: Re: [MutonUfoAI/pgina] Cant login to pGina Account (#35)
